image: atlassian/default-image:2

clone:
  depth: full

definitions:
  caches:
    gradle-wrapper: ~/.gradle/wrapper
  common-caches: &caches
    caches:
      - gradle
      - gradle-wrapper
  steps:
    - &check
      <<: *caches
      name: Check
      # language=sh
      script:
        - ./gradlew check sonar
    - &build
      <<: *caches
      name: Build
      # language=sh
      script:
        - ./gradlew build sonar
      artifacts:
        - build/**
    - &release
      <<: *caches
      name: Release
      # language=sh
      script:
        - git remote set-url origin $BITBUCKET_GIT_SSH_ORIGIN
        - ./gradlew sonar release -Prelease.releaseVersion=$RELEASE_VERSION -Prelease.newVersion=$NEW_VERSION

pipelines:
  default:
    - step: *check
  branches:
    master:
      - step: *release
  pull-requests:
    '**':
      - step: *check
  custom:
    release:
      - variables:
          - name: RELEASE_VERSION
          - name: NEW_VERSION
      - step: *release
