image: atlassian/default-image:2

clone:
  depth: full

definitions:
  caches:
    gradle-wrapper: ~/.gradle/wrapper
    gradle-notifications: ~/.gradle/notifications
    sonar: ~/.sonar/cache
  common-caches: &caches
    caches:
      - gradle
      - gradle-wrapper
      - gradle-notifications
      - sonar
  steps:
    - &check
      <<: *caches
      name: Check
      # language=sh
      script:
        - ./gradlew check sonar
    - &build
      <<: *caches
      name: Build
      # language=sh
      script:
        - ./gradlew build sonar
      artifacts:
        - build/**
    - &release
      <<: *caches
      name: Release
      # language=sh
      script:
        - git remote set-url origin "https://x-token-auth:$(curl -s -X POST -u "$BOT_CREDENTIALS" https://bitbucket.org/site/oauth2/access_token -d grant_type=client_credentials -d scopes="repository" | jq -r .access_token)@bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
        - ./gradlew sonar release -Prelease.useAutomaticVersion=true

pipelines:
  branches:
    master:
      - step: *release
  pull-requests:
    '**':
      - step: *check
  custom:
    release:
      - variables:
          - name: RELEASE_VERSION
          - name: NEW_VERSION
      - step: *release
